# Placeholder — the real font-config.sh is generated by font_module.compile_fonts()
# at build time and replaces this file in every packaged module.
# Variables provided at build time:
#   FONT_MODE       — 'static' or 'variable'
#   FONT_FAMILY     — detected font family name
#   FONT_FILES      — space-separated list of payload font files
#   VF_UPRIGHT_AXIS_META / VF_UPRIGHT_WEIGHTS    — Sans upright variable axis info
#   VF_ITALIC_AXIS_META / VF_ITALIC_WEIGHTS      — Sans italic variable axis info
#   VF_MONO_AXIS_META / VF_MONO_WEIGHTS          — Monospace axis info
#   VF_SERIF_UPRIGHT_AXIS_META / VF_SERIF_UPRIGHT_WEIGHTS  — Serif upright axis info
#   VF_SERIF_ITALIC_AXIS_META / VF_SERIF_ITALIC_WEIGHTS    — Serif italic axis info
#   VF_BENGALI_AXIS_META / VF_BENGALI_WEIGHTS    — Bengali axis info
#   (VF_* variables are set only when the family has a variable wght axis)
FONT_MODE='static'
FONT_FAMILY='Template'
FONT_FILES='DroidSans.ttf'
