# Placeholder — the real font-config.sh is generated by font_module.compile_fonts()
# at build time and replaces this file in every packaged module.
FONT_MODE='static'
FONT_FAMILY='Template'
FONT_FILES='DroidSans.ttf'
FONT_PRIMARY='DroidSans.ttf'
CLOCK_FONT='GoogleSansClock-Regular.ttf'
