# ==============================================================================
# MFFMv14 Generated Font Configuration
# Copyright © 2026 MFFM / Mistu
# Last modified: 2026-06-18
# Generated by build.py/update.py. Do not edit by hand.
# ==============================================================================
FONT_MODE='variable'
FONT_FAMILY='Uai Variable'
FONT_FILES='DroidSans.ttf'
FONT_PRIMARY='DroidSans.ttf'
CLOCK_FONT='GoogleSansClock-Regular.ttf'
VF_CONFIG_SCHEMA='2'
VF_UPRIGHT_AXIS_META='wght|100|445|900'
VF_ITALIC_AXIS_META='wght|100|445|900'
VF_UPRIGHT_WEIGHTS='100 200 300 400 500 600 700 800 900'
VF_ITALIC_WEIGHTS='100 200 300 400 500 600 700 800 900'
VF_CONFIG_ID='vf-3cd5e6797571296683f1'
