# ==============================================================================
# MFFMv14 Generated Font Configuration
# Copyright © 2026 MFFM / Mistu
# Last modified: 2026-06-18
# Generated by build.py/update.py. Do not edit by hand.
# ==============================================================================
FONT_MODE='variable'
FONT_FAMILY='Config Mono'
FONT_FILES='DroidSans.ttf DroidSans-Bold.ttf'
FONT_PRIMARY='DroidSans.ttf'
CLOCK_FONT='GoogleSansClock-Regular.ttf'
VF_CONFIG_SCHEMA='2'
VF_UPRIGHT_AXIS_META='wght|200|400|700'
VF_ITALIC_AXIS_META='wght|200|400|700'
VF_UPRIGHT_WEIGHTS='200 300 400 500 600 700'
VF_ITALIC_WEIGHTS='200 300 400 500 600 700'
VF_CONFIG_ID='vf-d95dce479c487e8ee4bf'
