# ==============================================================================
# MFFMv14 Generated Font Configuration
# Copyright © 2026 MFFM / Mistu
# Last modified: 2026-06-18
# Generated by build.py/update.py. Do not edit by hand.
# ==============================================================================
FONT_MODE='variable'
FONT_FAMILY='Anthropic Sans Variable'
FONT_FILES='DroidSans.ttf DroidSans-Bold.ttf'
FONT_PRIMARY='DroidSans.ttf'
CLOCK_FONT='GoogleSansClock-Regular.ttf'
VF_CONFIG_SCHEMA='2'
VF_UPRIGHT_AXIS_META='wght|300|400|800 opsz|16|16|48'
VF_ITALIC_AXIS_META='wght|300|400|800 opsz|16|16|48'
VF_UPRIGHT_WEIGHTS='300 400 500 600 700 800'
VF_ITALIC_WEIGHTS='300 400 500 600 700 800'
VF_CONFIG_ID='vf-61502e84b69c56f462b4'
